### ISSUE TITLE
ul and ol style not showing

### ISSUE THREAD

**Issue by jivimberg** [sevenadrian/MediumFox#7]
Hi!
I've noticed that using lists on markdown produces un-styled lists on the resulting page. 
My workaround is adding this lines to the `sass/custom/_layout.scss` file:

``` scss
@mixin fontStyle() {
   margin-left: 15px;
   font-weight: 300;
   font-size: 16px;
   line-height: 1.5;
}

.full-single-article ul {
    @include fontStyle();
    list-style: square inside;
}

.full-single-article ol {
    @include fontStyle();
    list-style: decimal inside;
}
```

This is only a workaround. I'll try to look for where this code should go in the theme project to fix it, any pointers will be appreciated.
